# Generated by Django 5.1.1 on 2024-09-20 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="about",
            new_name="password",
        ),
    ]
